server:
  port: 8888  # Config Server Port

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/habtomab/config-repo  # Replace with your Git repository URL
          default-label: main  # Replace with your branch name if needed
          search-paths: '{application}'
          clone-on-start: true
          username:   # Git username
          password:  # Git password (if required)

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.boot: WARN
    org.springframework.cloud.config.server: DEBUG


