server:
  port: 8888  # Config Server Port

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/habtomab/config-repo  # Git repo with configuration files
          default-label: main  # The branch where config files are stored
          search-paths:
            - configs

